"""Iter38r-fix9p — Public docs (PDF) download endpoints.

Three flagship documents generated by `/app/docs/generate_pdfs.py`:
  - A_Guide_Utilisateur_SAWALI_Loois.pdf
  - B_Brochure_Presentation_SAWALI_Loois.pdf
  - C_Brochure_Grandes_Fonctionnalites.pdf
"""
from __future__ import annotations
import asyncio
import logging
from pathlib import Path
from typing import Any, Callable, Dict, Optional
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse

logger = logging.getLogger("sawali.public_docs")

DOCS_DIR = Path("/app/docs")
DOCS = {
    "guide-utilisateur": "A_Guide_Utilisateur_SAWALI_Loois.pdf",
    "brochure-presentation": "B_Brochure_Presentation_SAWALI_Loois.pdf",
    "brochure-fonctionnalites": "C_Brochure_Grandes_Fonctionnalites.pdf",
    # S-iter39e — Référence technique AdminSettings (sans valeurs)
    "admin-settings-reference": "D_Documentation_Technique_AdminSettings.pdf",
}

# Iter38r-fix9s — Map each slug to its generator function (declared in generate_pdfs.py)
BUILDERS: Dict[str, str] = {
    "guide-utilisateur": "build_user_guide",
    "brochure-presentation": "build_presentation_brochure",
    "brochure-fonctionnalites": "build_features_brochure",
    "admin-settings-reference": "build_admin_settings_doc",
}


def setup_docs_routes(*, api: APIRouter, get_current_user: Optional[Callable] = None):
    @api.get("/public/docs", tags=["Public — Docs"])
    async def list_docs():
        items = []
        for slug, fname in DOCS.items():
            p = DOCS_DIR / fname
            if p.exists():
                items.append({
                    "slug": slug,
                    "filename": fname,
                    "size_kb": p.stat().st_size // 1024,
                    "url": f"/api/public/docs/{slug}",
                    "modified_at": p.stat().st_mtime,
                })
        return {"items": items}

    @api.get("/public/docs/{slug}", tags=["Public — Docs"])
    async def download_doc(slug: str):
        fname = DOCS.get(slug)
        if not fname:
            raise HTTPException(404, "Document inconnu")
        p = DOCS_DIR / fname
        if not p.exists():
            raise HTTPException(404, "Fichier non trouvé")
        return FileResponse(
            str(p),
            media_type="application/pdf",
            filename=fname,
            headers={"Content-Disposition": f'inline; filename="{fname}"'},
        )

    # Iter38r-fix9s — Admin-only regeneration (one slug or all)
    if get_current_user is not None:
        @api.post("/admin/docs/regenerate/{slug}", tags=["Admin — Docs"])
        async def regenerate_doc(slug: str, user: dict = Depends(get_current_user)):
            role = (user or {}).get("role")
            if role not in ("admin", "superviseur"):
                raise HTTPException(status_code=403, detail="Accès réservé aux administrateurs et superviseurs")
            builder_name = BUILDERS.get(slug)
            if not builder_name:
                raise HTTPException(status_code=404, detail="Slug inconnu")
            # Run the heavy reportlab build in a worker thread (CPU-bound)
            try:
                import sys
                sys.path.insert(0, str(DOCS_DIR))
                from generate_pdfs import (  # noqa: WPS433
                    build_user_guide,
                    build_presentation_brochure,
                    build_features_brochure,
                )
                from generate_admin_settings_doc import build_admin_settings_doc  # noqa: WPS433
                builders = {
                    "build_user_guide": build_user_guide,
                    "build_presentation_brochure": build_presentation_brochure,
                    "build_features_brochure": build_features_brochure,
                    "build_admin_settings_doc": build_admin_settings_doc,
                }
                builder = builders[builder_name]
                result_path: Path = await asyncio.to_thread(builder)
                size_kb = result_path.stat().st_size // 1024 if result_path.exists() else 0
                return {
                    "ok": True,
                    "slug": slug,
                    "filename": result_path.name,
                    "size_kb": size_kb,
                }
            except Exception as exc:
                logger.exception("[public_docs] regeneration failed for %s", slug)
                raise HTTPException(status_code=500, detail=f"Échec régénération : {exc}") from exc

    return api
