"""Iter38r-fix9k — Tests for KB OCR cost tracking, PDF OCR, notes
task_items (Google Keep), and strict tasks mode flag."""
from __future__ import annotations

import io
import os
import uuid

import pytest
import requests
from dotenv import load_dotenv
from pymongo import MongoClient


load_dotenv("/app/backend/.env")
BASE = (os.environ.get("REACT_APP_BACKEND_URL") or "http://127.0.0.1:8001").rstrip("/")
API = BASE + "/api"
ADMIN_EMAIL = "admin@sawalismartsystems.com"
ADMIN_PASS = "Admin@Sawali2026"


@pytest.fixture(scope="module")
def admin_h():
    r = requests.post(f"{API}/auth/login", json={"email": ADMIN_EMAIL, "password": ADMIN_PASS}, timeout=10).json()
    if r.get("needs_otp"):
        r = requests.post(f"{API}/auth/verify-otp",
                          json={"session_token": r["session_token"], "code": r["dev_otp"]},
                          timeout=10).json()
    token = r.get("access_token") or r.get("token")
    assert token, f"login failed: {r}"
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture(scope="module")
def db_sync():
    cli = MongoClient(os.environ["MONGO_URL"])
    yield cli[os.environ["DB_NAME"]]
    cli.close()


def test_kb_ocr_usage_endpoint_returns_zero_initially(admin_h, db_sync):
    # Clean current-month ai_usage for kb_ocr
    from datetime import datetime, timezone
    ym = datetime.now(timezone.utc).strftime("%Y-%m")
    db_sync.ai_usage.delete_many({"resource": "kb_ocr", "ym": ym})
    r = requests.get(f"{API}/admin/liluvine-pro/kb/ocr-usage", headers=admin_h, timeout=10)
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["pages"] == 0
    assert body["cost_xof"] == 0
    assert "monthly_cap_xof" in body
    assert "xof_per_page" in body


def test_kb_ocr_pdf_in_classic_mode_still_works(admin_h):
    """PDF classic mode (no force_ocr) should still accept PDFs."""
    try:
        import fitz
    except Exception:
        pytest.skip("PyMuPDF not installed")
    doc = fitz.open()
    page = doc.new_page()
    page.insert_text((72, 72), "PDF classic mode iter38r-fix9k content for native text extraction")
    pdf_bytes = doc.tobytes()
    doc.close()
    files = {"file": ("doc.pdf", pdf_bytes, "application/pdf")}
    data = {"title": "PDF classic fix9k"}
    r = requests.post(f"{API}/admin/liluvine-pro/kb/upload", headers=admin_h, files=files, data=data, timeout=15)
    # 200 if text extracted, 422 if no text — never 415 (image-only rejection)
    assert r.status_code in (200, 422), r.text


def test_kb_ocr_pdf_in_ocr_mode_now_supported(admin_h, db_sync):
    """Iter38r-fix9k — PDF in OCR mode should NOT be 415 anymore (now rasterized
    via PyMuPDF). The actual rasterize+Vision call is left to integration since
    it costs LLM credits."""
    # Real one-page PDF generated by PyMuPDF for a deterministic test
    try:
        import fitz
    except Exception:
        pytest.skip("PyMuPDF not installed")
    doc = fitz.open()
    page = doc.new_page()
    page.insert_text((72, 72), "Hello SAWALI Iter38r-fix9k OCR test")
    pdf_bytes = doc.tobytes()
    doc.close()
    # Ensure no cap blocks the call
    db_sync.settings.update_one(
        {"_id": "global"},
        {"$set": {"kb_ocr_xof_per_page": 50, "kb_ocr_xof_monthly_cap": 0, "kb_ocr_pdf_max_pages": 3}},
    )
    files = {"file": ("test.pdf", pdf_bytes, "application/pdf")}
    data = {"title": "PDF OCR fix9k", "force_ocr": "true"}
    r = requests.post(f"{API}/admin/liluvine-pro/kb/upload", headers=admin_h, files=files, data=data, timeout=120)
    assert r.status_code != 415, f"PDF should be accepted in OCR mode now: {r.text}"
    # Could be 200 (vision returned text) or 502 (LLM transient) — but NOT 415


def test_kb_ocr_monthly_cap_blocks_at_429(admin_h, db_sync):
    """When monthly cap is reached, OCR upload returns 429.
    Iter38r-fix9o (Item 2): cap is now per-tenant on user.features."""
    from datetime import datetime, timezone
    ym = datetime.now(timezone.utc).strftime("%Y-%m")
    admin = db_sync.users.find_one({"email": ADMIN_EMAIL})
    # Set tenant-level cap on the admin's user doc
    db_sync.users.update_one(
        {"id": admin["id"]},
        {"$set": {
            "features.kb_ocr_enabled": True,
            "features.kb_ocr_xof_per_page": 100,
            "features.kb_ocr_xof_monthly_cap": 100,
        }},
    )
    # Inject usage that reaches the cap (tagged with this tenant_id)
    db_sync.ai_usage.insert_one({
        "id": str(uuid.uuid4()),
        "resource": "kb_ocr",
        "model": "test",
        "units": 2,
        "cost_xof": 200,  # already over the cap
        "ym": ym,
        "kind": "image_ocr",
        "tenant_id": admin["id"],
        "created_at": "2026-05-30T18:00:00+00:00",
    })
    png_1x1 = bytes.fromhex(
        "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
        "0000000d49444154789c63f8cf00010000000005000150ff0a0000000049454e44ae426082"
    )
    files = {"file": ("blocked.png", png_1x1, "image/png")}
    data = {"title": "Should be blocked", "force_ocr": "true"}
    r = requests.post(f"{API}/admin/liluvine-pro/kb/upload", headers=admin_h, files=files, data=data, timeout=15)
    assert r.status_code == 429, r.text
    # Cleanup
    db_sync.ai_usage.delete_many({"resource": "kb_ocr", "ym": ym})
    db_sync.users.update_one(
        {"id": admin["id"]},
        {"$set": {"features.kb_ocr_xof_monthly_cap": 0, "features.kb_ocr_xof_per_page": 0}},
    )


def test_create_task_with_checklist_items(admin_h, db_sync):
    """POST /me/notes/tasks should persist task_items as an array."""
    payload = {
        "title": "Test checklist fix9k",
        "content_html": "<p>Note libre</p>",
        "task_items": [
            {"text": "Acheter du papier", "done": False, "order": 0},
            {"text": "Imprimer le contrat", "done": True, "order": 1},
        ],
    }
    r = requests.post(f"{API}/me/notes/tasks", headers=admin_h, json=payload, timeout=10)
    assert r.status_code == 200, r.text
    note = r.json()
    assert note["task_items"]
    assert len(note["task_items"]) == 2
    assert all(it.get("id") for it in note["task_items"])  # IDs auto-generated
    # Cleanup
    db_sync.user_tasks_personal.delete_one({"id": note["id"]})


def test_update_task_toggles_done(admin_h, db_sync):
    """PUT /me/notes/tasks/{id} should update task_items (toggle done)."""
    payload = {
        "title": "Toggle test fix9k",
        "task_items": [{"text": "Item 1", "done": False, "order": 0, "id": "item-1"}],
    }
    r = requests.post(f"{API}/me/notes/tasks", headers=admin_h, json=payload, timeout=10)
    note = r.json()
    nid = note["id"]
    # Toggle
    payload_upd = {"task_items": [
        {"text": "Item 1", "done": True, "order": 0, "id": "item-1", "done_at": "2026-05-30T19:00:00+00:00"}
    ]}
    r2 = requests.put(f"{API}/me/notes/tasks/{nid}", headers=admin_h, json=payload_upd, timeout=10)
    assert r2.status_code == 200, r2.text
    doc = db_sync.user_tasks_personal.find_one({"id": nid})
    assert doc["task_items"][0]["done"] is True
    assert doc["task_items"][0]["id"] == "item-1"
    db_sync.user_tasks_personal.delete_one({"id": nid})


def test_features_exposes_notes_strict_tasks_only(admin_h, db_sync):
    """/me/features should expose the notes_strict_tasks_only tenant flag."""
    db_sync.settings.update_one({"_id": "global"}, {"$set": {"notes_strict_tasks_only": True}})
    r = requests.get(f"{API}/me/features", headers=admin_h, timeout=10)
    assert r.status_code == 200
    feats = r.json()["features"]
    assert feats.get("notes_strict_tasks_only") is True
    # Reset
    db_sync.settings.update_one({"_id": "global"}, {"$set": {"notes_strict_tasks_only": False}})


def test_settings_persists_notes_strict_tasks_only(admin_h, db_sync):
    r = requests.put(f"{API}/admin/settings", headers=admin_h,
                     json={"notes_strict_tasks_only": True}, timeout=10)
    assert r.status_code == 200, r.text
    s = db_sync.settings.find_one({"_id": "global"})
    assert s["notes_strict_tasks_only"] is True
    db_sync.settings.update_one({"_id": "global"}, {"$set": {"notes_strict_tasks_only": False}})
